# Provider network interface, e.g. eth3
# general (krushaaa).conf
ISP_INTERFACE="eth2.2"

# Startup arguments
NFQWS_BASE_ARGS="
                 --lua-init=@/opt/etc/nfqws2/lua/zapret-lib.lua \
                 --lua-init=@/opt/etc/nfqws2/lua/zapret-antidpi.lua \
                 --lua-init=@/opt/etc/nfqws2/lua/zapret-auto.lua \
                 --blob=quic_lordfilm:@/opt/etc/nfqws2/blobs/quic_lordfilm.bin
                 --blob=tls_google:@/opt/etc/nfqws2/blobs/tls_clienthello_www_google_com.bin
                 --blob=tls_lordfilm:@/opt/etc/nfqws2/blobs/tls_lordfilm.bin
                 --blob=stun2_fake:@/opt/etc/nfqws2/blobs/stun.bin
                 --blob=discord_udp:@/opt/etc/nfqws2/blobs/ACTIVE_DISCORD_UDP.bin \
                 --blob=game_udp:@/opt/etc/nfqws2/blobs/ACTIVE_GAME_UDP.bin
                 --fastpath-workaround=auto"

# HTTP(S) strategy  Если много TLS DROP в прогоне, меняйте кол-во повторов (repeats) от 4 до 14
NFQWS_ARGS="     --filter-tcp=80,443 --filter-l7=http,tls \
                 --payload=tls_client_hello \
                 --lua-desync=fake:blob=stun2_fake:repeats=8:tcp_ts=-600000:tcp_ts_up \
                 --lua-desync=fakedsplit:pos=midsld:tcp_ack=-66000:tcp_ts_up:seqovl=417:seqovl_pattern=0x1603010000
                 --lua-desync=fake:blob=tls_lordfilm:repeats=8:tcp_ts=-600000:tcp_ts_up \
                 --lua-desync=multisplit:pos=100,midsld-2,endhost-4:repeats=8:seqovl=681:seqovl_pattern=tls_google \
                 --payload=http_req \
                 --lua-desync=fake:blob=stun2_fake:repeats=8:tcp_ts=-600000:tcp_ts_up \
                 --lua-desync=fakedsplit:pos=midsld:tcp_ack=-66000:tcp_ts_up:seqovl=417:seqovl_pattern=0x1603010000
                 --lua-desync=fake:blob=tls_lordfilm:repeats=8:tcp_ts=-600000:tcp_ts_up \
                 --lua-desync=multisplit:pos=100,midsld-2,endhost-4:repeats=8:seqovl=681:seqovl_pattern=tls_google

            
# QUIC strategy  В случае не работы ютуба меняем outrange от 3 до 8, repeats от 4 до 14
NFQWS_ARGS_QUIC="--filter-udp=443 --filter-l7=quic \
                 --out-range=-n8
                 --payload=quic_initial \
                 --lua-desync=fake:blob=quic_lordfilm:repeats=11"

# UDP strategy  Строго дискорд , если хотите что то добавить делайте кастом , изменение портов здесь карается 5к пингом
NFQWS_ARGS_UDP="--filter-udp=19294-19344,50000-65535 --filter-l7=discord,stun \
                --payload=discord_ip_discovery,stun \
                --lua-desync=fake:blob=discord_udp:repeats=6"

# Working modes
MODE_LIST="--hostlist=/opt/etc/nfqws2/lists/user.list"
MODE_ALL="--hostlist-exclude=/opt/etc/nfqws2/lists/exclude.list"
MODE_AUTO="$MODE_LIST --hostlist-auto=/opt/etc/nfqws2/lists/auto.list --hostlist-auto-debug=/opt/var/log/nfqws2.log $MODE_ALL"
NFQWS_EXTRA_ARGS="$MODE_AUTO"

# IP-lists
NFQWS_ARGS_IPSET="--ipset=/opt/etc/nfqws2/lists/ipset.list --ipset-exclude=/opt/etc/nfqws2/lists/ipset_exclude.list"

# Custom arguments
NFQWS_ARGS_CUSTOM=""
#Для будующих кастомов                           
                #Youtube                          
                #Discord(web)
                #Discord(RTC)
                #Akamai
                #Amazon
                #CDN77
                #CloudFlare
                #Contabo
                #DigitalOcean
                #Frantech
                #Hetzer
                #OracleCloud
                #OVH
                #Scaleway
                #Telegram
                #DNS 

# IPv6 support
IPV6_ENABLED=1

# TCP ports for iptables rules
TCP_PORTS=80,443,853,

# UDP ports for iptables rules
UDP_PORTS=443,853,19294:19344,50000:65535

# Keenetic policy name
POLICY_NAME="nfqws"
POLICY_EXCLUDE=0
LOG_LEVEL=0
LOG_DEBUG_PATH="@/opt/var/log/nfqws2-debug.log"
NFQUEUE_NUM=300
USER=nobody
CONFIG_VERSION=1

